### ISSUE TITLE
remove need to call bind() on UDP sockets

### ISSUE THREAD

**Issue by trevj** [freedomjs/freedom#88] opened 2014-08-01 18:36 UTC
Unlike with BSD sockets, you have to call `bind()` before `sendTo()` even if you don't care from which outbound socket your traffic originates.

Since the interface looks almost exactly like BSD sockets, it's probably not unreasonable to expect it to behave like them too.

Probably just involves removing the comment here, and checking the implementations do the right thing: 
https://github.com/freedomjs/freedom/blob/master/interface/core.js#L205

**Comment by willscott** [comment] 2015-01-21 19:16
This is also true in many flavors of linux http://stackoverflow.com/a/3057797

Lets close this as 'working as intended'. Can be reopened once the underlying firefox & chrome implementations both decide to allow dynamic binding behavior in their APIs.

**Closed by willscott** 2015-01-21 19:16 UTC

**Comment by iislucas** [comment] 2015-01-22 23:41
I'd suggest documenting it in API docs before closing it, else you're likely to loose track.

**Comment by willscott** [comment] 2015-01-22 23:43
The documentation saying that calls to bind() are needed continues to exist
in the same form as was referenced in the initial bug report.

**Comment by iislucas** [comment] 2015-01-22 23:55
The original link is now broken :) 

This is now the location that I think is relevant: https://github.com/freedomjs/freedom/blob/master/interface/core.udpsocket.json#L54 

The closest you've got is this: 
https://github.com/freedomjs/freedom/blob/master/interface/core.udpsocket.json#L2

But I think the discussion here adds a bit to that. e.g. it does not seem to say in the comments of sendTo that a bind is needed first. And in the freedomjs.org wiki docs, there also doesn't seem to be a description of the udp interface.
